### PR TITLE
Add @akaszynski as maintainer

### PR DESCRIPTION
**Pull request by banesullivan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by banesullivan** [comment]
@conda-forge-admin, please rerender

**Comment by banesullivan** [comment]
@akaszynski, do you consent to being notified by this repo for life?

**Comment by akaszynski** [comment]
> @akaszynski, do you consent to being notified by this repo for life?

Yes.  Would be helpful to be informed.

**Comment by banesullivan** [comment]
I think I just merge this and it'll work? we'll see

**Pull request merged**
